### ISSUE TITLE
Suggested resources for Peewee ORM

### ISSUE THREAD

**Issue by coleifer** [makaimc/fullstackpython.com#56]
First of all, thanks for your awesome site. This is a fantastic resource for the community, well-written, up-to-date, well-maintained and well-organized. Nice work!

I have just a couple suggestions for resources that people may find useful for learning or using Peewee ORM.

[Dear Diary, an Encrypted Command-Line Diary with Python](http://charlesleifer.com/blog/dear-diary-an-encrypted-command-line-diary-with-python/): this post has been really popular. It is very concise yet manages to show off a number of cool peewee features. The folks at Team Treehouse liked it so much they based their Python ORMs/Database class on the post! So I think it'd be a good one to add to the list.

Not sure if you think it's redundant, but the documentation's [quickstart](http://docs.peewee-orm.com/en/latest/peewee/quickstart.html) and the [building a twitter app](http://docs.peewee-orm.com/en/latest/peewee/example.html) might be helpful. If you were to only include one, I think the "Twitter" one would be the best.

I hope you'll consider adding these resources to the Peewee section as they get a lot of traffic and seem to be useful to folks.

**Comment by makaimc** [comment]
Thank you Charles, I really appreciate the feedback! The work you're doing on Peewee is awesome - I love having new(er) projects put forth their own philosophy and approaches when the general consensus is highly invested in existing projects, such as Django ORM & SQLAlchemy. The diversity of the ecosystem is really important and you're doing a damn fine job of coding & showing off Peewee.

I've added these 3 resources to the ORMs page under "Peewee resources". When you have more of them in the future, issues or PRs are great. If you're ever out in the Bay Area, let me know so I can buy you lunch. Thanks again!

**Comment by coleifer** [comment]
Thanks man, I take your compliment to heart! Thanks for adding the links, I think they will be helpful to folks.
