### ISSUE TITLE
How to bind domain to project's gh-pages?

### ISSUE THREAD

**Issue by xuehao** [makaimc/fullstackpython.com#61]
Dear Makaimc,
I just can bind my domain `www.xxx.com` to `myname.github.io`
How can you bind `www.fullstackpython.com` to this gh-pages?

**Comment by makaimc** [comment]
Hi @xuehao, there's a [CNAME file](https://github.com/makaimc/fullstackpython.com/blob/gh-pages/CNAME) in the root folder of the gh-pages branch that contains www.fullstackpython.com in it. Then you need to point your DNS record to username.github.io (where username is your username). Check out [this guide](https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/) for more information.
