### ISSUE TITLE
new source

### ISSUE THREAD

**Issue by doomedraven** [makaimc/fullstackpython.com#78]
Hello
probably you know, but just in case, If you don't know this is really nice sources, and i think it would be good mention it in your page :)

http://www.doughellmann.com/PyMOTW/contents.html

**Comment by makaimc** [comment]
good one @doomedraven, especially now that Doug is now putting out updates for Python 3. I'll add this to the [Best Python Resources(https://www.fullstackpython.com/best-python-resources.html) page later today.
