### ISSUE TITLE
You may want to include this base Docker image for Flask

### ISSUE THREAD

**Issue by tiangolo** [makaimc/fullstackpython.com#79]
I made a public (and open source) Docker image with all the bells and whistles that people can use to build a Python Flask web application.

It has uWSGI for running the application, Nginx to serve HTTP and Supervisord to control them, so people don't have to learn how to install and configure all those to build a Python Flask web app. 

If there was a Docker image like this one before, I would have liked to find it in your page, so I share this with you in case you want to include it.

It seems that uWSGI and Nginx is one of the more robust and performant ways to deploy a Python web app (here the benchmarks): <http://nichol.as/benchmark-of-python-web-servers>.

There are even some template projects people can use to bootstrap their own. And also, they don't have to clone the full project or something, they can just use it as a base image.

Docker Hub: <https://hub.docker.com/r/tiangolo/uwsgi-nginx-flask/>
GitHub: <https://github.com/tiangolo/uwsgi-nginx-flask-docker>

And thanks for a great guiding site!

**Comment by makaimc** [comment]
:+1: cool, looks good! I've added it to the Docker page and it should be live in a minute or so

**Comment by tiangolo** [comment]
Cool, thanks!
