### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by jlmenut** [makaimc/fullstackpython.com#82]
Hello, 
I was reading the  _Django books and tutorials_  chapter on the  _https://www.fullstackpython.com/django.html_ page and I found some dead links/

 Lightweight Django (http://ww1.lightbird.net/dbe2/) and Django: Wall of Superpowers! (http://djangowos.com/) are completely dead. 

The page Lincoln Loop's  Django Best Practices  (http://lincolnloop.com/django-best-practices/)  is not showing the guide  anymore but a list of books (and a link to the github of the old page) 

And the address of Deploying Django on AWS (https://nickpolet.com/blog/deploying-django-on-aws/) seems to have changed to https://nickpolet.com/blog/deploying-django-on-aws/koAayBejnjdNwYfc6

**Comment by makaimc** [comment]
Thank you @jlmenut! Bummer to see those links go down. I run a scanner every few weeks to make sure there are no 404's linked to, but when the content itself changes to something else I often don't catch it. Your issue request is a huge help in keeping these pages up to date - these are all fixed and the new page is live now.
