### ISSUE TITLE
Main table of contents  is not consistent with the one in sidebar.

### ISSUE THREAD

**Issue by haiiiiiyun** [makaimc/fullstackpython.com#89]
[Main table of contents](http://www.fullstackpython.com/table-of-contents.html) is not consistent with the [one in sidebar](http://www.fullstackpython.com/vim.html).

**Comment by makaimc** [comment]
That's true. I'm expanding to new pages over time so there are gaps in how the topics are organized. I'm actually not concerned about this for now - I'll reorganize after more new pages are created. Will close this ticket for now.
