### ISSUE TITLE
Link broken on page 02-web-frameworks.markdown

### ISSUE THREAD

**Issue by haiiiiiyun** [makaimc/fullstackpython.com#90]
> This [Python web framework roundup](http://www.konstruktor.ee/blog/python-web-framework-roundup/)
>   covers Django, Flask and Bottle as well as several other lesser known Python
>   frameworks.

link http://www.konstruktor.ee/blog/python-web-framework-roundup/ broken.

**Comment by makaimc** [comment]
thank you @haiiiiiyun, this is really helpful. I check for broken links that return a 404 but it takes me a bit longer to catch pages that return a 200 result but aren't the appropriate content. should be fixed now
